# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23d33b10fa7e2c57ab830b66d6efe80b402550f2507ac35c6afdb44657406b20ca31f56ed72b2398cd5920f6b23728647d301c939ce737efe61696680a64399

test:
  secret_key_base: 95b0fe65aebd8fbb9f39c93c186d14a6fa6745716a64e1f6d3aa1b9c2d6619abeeabacb5b4207053b43021f7e8dbe7bad59f8d5a0a0181ddcdb811888bd87fff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
